### ISSUE TITLE
Error continuum subtraction with mask

### ISSUE THREAD

**Issue by ruffai** [SpheMakh/contsub#4]
I'm trying to run imcontsub on a MeerKAT cube giving as input the clean mask, and this is the error I'm getting:

(imcontsub) i.ruffa@merlino2:/local/work/fmaccagni/reduced_nb/NGC3557/galx/output/cubes/cube_1$ imcontsub --mask-image /local/work/fmaccagni/reduced_nb/NGC3557/galx/output/masking/NGC3557_r10_t90_3kms_3kms_cleanmask_1_mask_comb_full_depth_regrid.fits comb_full_depth_NGC3557_HI_r05_t60_3kms_mg095_2.image.fits
Usage: imcontsub [OPTIONS] INPUT_IMAGE
Try 'imcontsub --help' for help.

Error: Invalid value for '--order': can't convert to 'List[int]'

Did something changed in the way imcontsub have to be launched?

**Comment by Fil8** [comment]
i tried multiple installations with python3.12 or python3.10 but I get the same error. While I still have a working version from March 2024
